# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f4fbe5eadd446d4ff11e7fe0aa2b9c251e6b55d0b20ab7bc08288c4ba2ff2455f8b0b7bc71cf8b4047cff168cffa9a1308fe1aba741ed9450ceee9bcc44192f

test:
  secret_key_base: 906d9a25dc3065f0dc3eaedadd68ac37993676b8d9f48b185f5b78b4fa429c1e3a875fb5632561c5ae6a04b0c9359d9496b590ad91b9ef34dfa939395b1746e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
